from setuptools import setup

setup(
    name='fmIDE',
    version='1.0',
    packages=['src', 'src.Main', 'src.Tests', 'src.Tests.pickles', 'src.Pickles', 'src.Entities', 'src.Entities.Line',
              'src.Entities.Shape', 'src.Entities.Format', 'src.Entities.Selection', 'src.Entities.Connection',
              'src.Entities.Selections', 'src.Entities.Worksheets', 'src.Entities.InputRanges',
              'src.Entities.InputValues', 'src.Entities.ShapeFormat', 'src.Entities.AccountOrder',
              'src.Entities.NumberFormat', 'src.Entities.AccountOrders', 'src.Entities.AccountValues',
              'src.Entities.ConnectionIDs', 'src.Entities.InputDecimals', 'src.Entities.VerticalAccounts',
              'src.Entities.RectangleSelector', 'src.Presenter', 'src.Presenter.Macros', 'src.Presenter.States',
              'src.Presenter.AddShape', 'src.Presenter.Commands', 'src.Presenter.DrawLine', 'src.Presenter.Template',
              'src.Presenter.MoveShape', 'src.Presenter.InputEntry', 'src.Presenter.Worksheets',
              'src.Presenter.ClearCanvas', 'src.Presenter.RemoveShape', 'src.Presenter.ConnectShape',
              'src.Presenter.FeedbackUser', 'src.Presenter.DrawRectangle', 'src.Presenter.HighlightShape',
              'src.Presenter.UpdateAccountOrder', 'src.Presenter.UpdateAccountsList',
              'src.Presenter.LoadPickleFilesList', 'src.Presenter.UpdateConnectionIDs',
              'src.Presenter.PresenterPassThrough', 'src.Presenter.UpdateShapeProperties',
              'src.Presenter.UpdateAccountsListWithDeltas', 'src.Resources', 'src.Utilities', 'src.Utilities.Graphs',
              'src.Utilities.Memento', 'src.ViewModel', 'src.Controller', 'src.Controller.MouseController',
              'src.Interactor', 'src.RequestModel', 'src.EntityGateway', 'src.ResponseModel', 'src.BoundaryOutput',
              'src.ExternalSystems', 'src.ExternalSystems.Configurations',
              'src.ExternalSystems.Configurations.ConfigTest', 'src.ExternalSystems.UserDefinedFunction',
              'src.ExternalSystems.UserDefinedFunction.Test', 'src.PicklesCommands', 'Templates'],
    url='',
    license='',
    author='STTM',
    author_email='',
    description=''
)
